[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@react-email/render"]

# Temporarily removing all redirects to test direct function access

[build.environment]
  NODE_VERSION = "18"