[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@react-email/render"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Remove the catch-all redirect that was interfering with CORS

[build.environment]
  NODE_VERSION = "18"